services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: usml
      POSTGRES_PASSWORD: usmlpass
      POSTGRES_DB: usml_db
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
